### PR TITLE
fix l10n_ch_payment_slip report write problem

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by jcoux — APPROVED** [review]
Code review only.
LGTM :+1:

**Review by leemannd — APPROVED** [review]
Thanks

**Review by tschanzt — APPROVED** [review]
looks good.

**Comment by yvaucher** [comment]
This one is already done in the main PR, thanks for reporting it.

In the mean time I did a couple of fixes to make the whole thing work.

**Pull request closed without merging**
